// UK lang variables

// for the Labels on creation pages
/// Form.htm
tinyMCELang['lang_insert_form_title'] = 'Form';
tinyMCELang['lang_insert_form_name'] = 'Form Name';
tinyMCELang['lang_insert_form_id'] = 'ID';
tinyMCELang['lang_insert_form_action'] = 'Action';
tinyMCELang['lang_insert_form_method'] = 'Method';
tinyMCELang['lang_insert_form_POST'] = 'POST';
tinyMCELang['lang_insert_form_GET'] = 'GET';
tinyMCELang['lang_insert_form_name'] = 'Form Name';
tinyMCELang['lang_insert_form_enctype'] = 'Encoding Type';
tinyMCELang['lang_insert_form_urlencoded'] = 'application/x-www-form-urlencoded';
tinyMCELang['lang_insert_form_formdata'] = 'multipart/form-data';
tinyMCELang['lang_insert_form_class'] = 'Class';
///textbox.htm
tinyMCELang['lang_insert_field_title'] = 'Insert/Modify field: ';
tinyMCELang['lang_field_type_text'] = 'Text Box';
tinyMCELang['lang_field_type_checkbox'] = 'Check Box';
tinyMCELang['lang_field_type_radio'] = 'Radio Button';
tinyMCELang['lang_field_type_password'] = 'Password Box';
tinyMCELang['lang_field_type_hidden'] = 'Hidden';
tinyMCELang['lang_field_type_submit'] = 'Submit Button';
tinyMCELang['lang_field_type_reset'] = 'Reset Button';
tinyMCELang['lang_field_type_button'] = 'Button';
tinyMCELang['lang_field_type_file'] = 'File Upload';
tinyMCELang['lang_field_type_image'] = 'Image';
tinyMCELang['lang_field_type_select'] = 'Select Box';
tinyMCELang['lang_field_attr_name'] = 'Name';
tinyMCELang['lang_field_attr_value'] = 'Value';
tinyMCELang['lang_field_attr_default_value'] = 'Default value';
tinyMCELang['lang_field_attr_size'] = 'Size';
tinyMCELang['lang_field_attr_maxlen'] = 'Maximum Length';
tinyMCELang['lang_field_attr_checked'] = 'Checked';
tinyMCELang['lang_field_attr_border'] = 'Border';
tinyMCELang['lang_field_attr_srcSRC'] = 'Source';
tinyMCELang['lang_field_attr_altALT'] = 'Alt';
tinyMCELang['lang_field_attr_lowsrc'] = 'Low Source';
tinyMCELang['lang_field_attr_width'] = 'Width';
tinyMCELang['lang_field_attr_height'] = 'Height';
tinyMCELang['lang_field_attr_align'] = 'Align';
tinyMCELang['lang_field_attr_vspace'] = 'Vertical Space';
tinyMCELang['lang_field_attr_hspace'] = 'Horizontal Space';
tinyMCELang['lang_field_attr_readonly'] = 'Read Only';
tinyMCELang['lang_field_attr_disabled'] = 'Disabled';
tinyMCELang['lang_field_attr_autocomplete'] = 'AutoComplete';
tinyMCELang['lang_field_attr_multiple'] = 'Multiple';
tinyMCELang['lang_field_options'] = 'Options';
tinyMCELang['lang_field_selected'] = 'Selected';
tinyMCELang['lang_field_displayed'] = 'Displayed Values';
tinyMCELang['lang_field_submitted'] = 'Submitted Values';

// button descriptions
tinyMCELang['lang_form_desc'] = 'Inserts a new form';
tinyMCELang['lang_form_select_desc'] = 'Edit/Insert a Drop Down Menu';
tinyMCELang['lang_form_textbox_desc'] = 'Edit/Insert a Text Box';
tinyMCELang['lang_form_property_desc'] = 'Edit Field Properties';
tinyMCELang['lang_form_textarea_desc'] = 'Edit/Insert a Text Area';
tinyMCELang['lang_form_checkbox_desc'] = 'Edit/Insert a Checkbox';
tinyMCELang['lang_form_radio_desc'] = 'Edit/Insert a Radio Button';
tinyMCELang['lang_form_password_desc'] = 'Edit/Insert a Password Box';
tinyMCELang['lang_form_hidden_desc'] = 'Edit/Insert a Hidden Field';
tinyMCELang['lang_form_submit_desc'] = 'Edit/Insert a Submit Button';
tinyMCELang['lang_form_reset_desc'] = 'Edit/Insert a Reset Button';
tinyMCELang['lang_form_file_desc'] = 'Edit/Insert a File Upload';
tinyMCELang['lang_form_image_desc'] = 'Edit/Insert an Image Button ';
tinyMCELang['lang_form_button_desc'] = 'Edit/Insert a Button';
tinyMCELang['lang_form_legend_desc'] = 'Group Fields Together';
tinyMCELang['lang_form_more_options'] = 'More Options';

// Help Descriptions
tinyMCELang['lang_form_help']      = '&lt;FORM ...&gt; indicates the beginning of a form. All other form tags go inside &lt;FORM ...&gt;. In its simplest use, &lt;FORM ...&gt; can be used without any attributes. Most forms require either the ACTION or NAME attributes to do anything meaningful.';
tinyMCELang['lang_form_help_nopreview']      = 'No preview available';
tinyMCELang['lang_form_help_novisable']      = 'Does not visably appear in the page';
tinyMCELang['lang_form_help_default']      = 'As you fill in the values in this window, help will appear hereAs you fill in the values in this window, help will appear here';
tinyMCELang['lang_form_help_select']      = '&lt;SELECT ...&gt; creates a list of options, one or more of which can be selected. In its simplest use, it consists of &lt;SELECT ...&gt;, two or more &lt;OPTION ...&gt; tags, and &lt;/SELECT&gt;. By default only one option can be selected. To have a list which allows more than one option, use the MULTIPLE attribute. See MULTIPLE for more details about this type of list.';
tinyMCELang['lang_form_help_options']      = '&lt;OPTION ...&gt; is used along with &lt;SELECT ...&gt; to create select lists. &lt;OPTION ...&gt; indicates the start of a new option in the list. &lt;OPTION ...&gt; can be used without any attributes, but you usually need the VALUE attribute, which indicates what is sent to the server.';
tinyMCELang['lang_form_help_checkbox']      = 'CHECKBOX creates a checkbox which can be either on or off. CHECKBOX is often used in groups to indicate a series of choices any one of which can be on or off. By default, the checkbox is initially off. If you want the checkbox initially on, use the CHECKED attribute. Checkbox CHECKBOXs are only sent to the CGI if they are on; if they are off, no name/value pair is sent.';
tinyMCELang['lang_form_help_radio']      = 'RADIO is used to create a series of choices of which only one can be selected. The term "radio button" comes from the buttons for the radio in an automobile, where selecting one radio station automatically de-selects all the others. HTML radio buttons are created by using several &lt;INPUT TYPE=RADIO&gt; buttons, all with the same name, but with different values.Note that it is the content of the VALUE attribute that is sent to the CGI, not whatever text happens to appear next to the radio button. If one of the items should be the default selection, use the CHECKED attribute. If no CHECKED attribute is used, different browsers have different ways of displaying the initial state of a series of radio buttons.';
tinyMCELang['lang_form_help_text']      = 'TEXT creates a text entry field (the most popular type of data entry field). TEXT is the default input type (if you want a text field, you don\'t even need to use the TYPE attribute).';
tinyMCELang['lang_form_help_password']      = 'PASSWORD indicates that the field is for typing in a password. PASSWORD works just like a TEXT type field, with the difference that whatever is typed is not displayed the screen (in case someone is watching over your shoulder or you have to leave the work station). Instead of showing what you typed in, the browser displays a series of asterisks (*), bullets (·), or something to show that you are typing, but not what you are typing. Note that PASSWORD fields are not sent encrypted, they are sent in the same manner as all the other elements on the form: in the clear. Note also that when you use PASSWORD you should also set the form METHOD to POST.';
tinyMCELang['lang_form_help_hidden']      = 'HIDDEN indicates that the field is invisible and the user never interacts with it. The field is still sent to the CGI, and scripts can also use the hidden field. HIDDEN is commonly used as output of a CGI which creates a new form for more input.';
tinyMCELang['lang_form_help_submit']      = 'SUBMIT creates the "Submit" button which sends the form in to the CGI. In its simplest form, you can use SUBMIT and no other attributes for the &lt;INPUT ...&gt; tag. You can customize the text used for the button using the VALUE attribute. You may sometimes find that you want to have more than one submit button on a form. If you give each button the same name, but different values, the browser will indicate which submit button was pressed.';
tinyMCELang['lang_form_help_reset']      = 'RESET resets the form so that it is the way it was before anything was typed in. For a while it was the perception that all forms "had" to have a reset button, but designers have found that resets are more likely to detract from the form than add to it. Users don\'t usually need to reset their forms, and they are more likely to accidentally hit the reset button than they are to actually want to wipe out their work. Unless you have a specific reason to expect that users will need a reset button it\'s probably best to leave it out. If you do choose to use have a reset button in your form, consider adding a check if the user actually wants to reset. You can do this by adding an onReset event handler to the &lt;FORM ...&gt; tag. If you add the VALUE attribute to the tag then that value is used as the text for the button.';
tinyMCELang['lang_form_help_button']      = 'BUTTON defines a button which causes a script to run. Use the onClick attribute to give the script command(s). BUTTON is used only with scripting. Browsers that don\'t understand scripts don\'t understand this type of input and usually render it as a text input field.';
tinyMCELang['lang_form_help_file']      = 'FILE is used for doing file uploads in a form. File uploads allow you to send an entire file from your computer to the web server as part of your form input. Configuring a form for file uploads requires setting two attributes in the &lt;FORM ...&gt; tags in addition to using &lt;INPUT TYPE=FILE&gt;: POST and "multipart/form-data" (as in the example above). When the data is sent, the original file name (including the full path) of the file as it was on your computer is sent to the web server. The CGI, however, is free to save the file as anything it wants -- or to not save it at all.';
tinyMCELang['lang_form_help_form_name']    = 'NAME gives a name to the form. This is most useful in scripting, where you frequently need to refer to the form in order to refer to the element within the form.';
tinyMCELang['lang_form_help_form_id']      = 'ID gives a identification to the form block. This is most useful in scripting, where you frequently need to refer to the form in order to refer to the element within the form.';
tinyMCELang['lang_form_help_form_action']  = 'ACTION gives the URL of the CGI program which will process this form.';
tinyMCELang['lang_form_help_form_method']  = 'METHOD specifies the method of transferring the form data to the web server. METHOD can be either GET or POST. Each method has its advantages and disadvantages.';
tinyMCELang['lang_form_help_form_enctype'] = 'In most cases you will not need to use this attribute at all. The default value (i.e. if you don\'t use this attribute at all) is "application/x-www-form-urlencoded", which is sufficient for almost any kind of form data. The one exception is if you want to do file uploads. In that case you should use "multipart/form-data".';
tinyMCELang['lang_form_help_form_class']   = 'Class styles enable you to set-up an independent style that can be applied to any HTML tag. A class is given unique name which can be added to any tags with the style attribute.';
tinyMCELang['lang_form_help_form_update']  = 'Save your changes to the main window';
tinyMCELang['lang_form_help_form_cancel']  = 'Abort your changes and return to the main window';
tinyMCELang['lang_help_field_attr_name'] = 'The Field Name. This value is not displayed in the form';
tinyMCELang['lang_help_field_attr_value'] = 'The initial value in the field';
tinyMCELang['lang_help_field_attr_size'] = 'How wide the text field should be';
tinyMCELang['lang_help_field_attr_maxlen'] = 'Maximum number of characters a user can input';
tinyMCELang['lang_help_field_attr_checked'] = 'Check this checkbox or radio button';
tinyMCELang['lang_help_field_attr_border'] = 'Border around image';
tinyMCELang['lang_help_field_attr_srcSRC'] = 'URL of image';
tinyMCELang['lang_help_field_attr_altALT'] = 'Text to show if you don\'t show the picture';
tinyMCELang['lang_help_field_attr_lowsrc'] = 'Version of the picture that isn\'t such a big file';
tinyMCELang['lang_help_field_attr_width'] = 'Width of image';
tinyMCELang['lang_help_field_attr_height'] = 'Height of image';
tinyMCELang['lang_help_field_attr_align'] = 'How text should flow around the picture';
tinyMCELang['lang_help_field_attr_vspace'] = 'Vertical distance between the picture and the text';
tinyMCELang['lang_help_field_attr_hspace'] = 'Horizontal distance between the picture and the text';
tinyMCELang['lang_help_field_attr_readonly'] = 'This field cannot be changed by the user';
tinyMCELang['lang_help_field_attr_disabled'] = 'Don\'t let the user do anything with this field';
tinyMCELang['lang_help_field_attr_autocomplete'] = 'Should browser use autocompletion on this field';
tinyMCELang['lang_help_field_attr_multiple'] = 'MULTIPLE designates that more than one option in the list can be selected.';
tinyMCELang['lang_help_field_attr_select_size'] = 'SIZE indicates how many rows of the list should be displayed. The default is one.';
tinyMCELang['lang_help_field_attr_selected'] = 'SELECTED indicates that the option should be selected by default.';
tinyMCELang['lang_help_field_attr_select_display'] = 'Displayed Value indicates the value that is displayed in the selection box.';
tinyMCELang['lang_help_field_attr_select_submitted'] = 'Submitted Value indicates the value that is sent to the server if that option is chosen.';
tinyMCELang['lang_help_field_attr_select_more'] = 'Add another set of option fields to this form';
